### ISSUE TITLE
Silent Mode Toggle

### ISSUE THREAD

**Issue by Albertino** [donnfelker/AndroidCodeExamples#1]
Hi Don,

I followed your example (great, btw!), but I believe I've found a couple of issues, though:
1. Every time a widget is added to the main screen, it changes the mode automatically to the next in sequence (since it executes "private RemoteViews buildUpdate(Context context)").
2. If the mode is modified from the Android settings, the view of the application detects the change, but this is not the case of the widget. That is, if I change the mode from the settings or from the application, the widgets doesn't refresh the icon.

Maybe I'm doing something wrong, if this is the case please excuse me and correct me :-)

My email is: albert.pt@gmail.com

Best regards,
Albert

**Comment by donnfelker** [comment]
Hello Albertino,

You're assumption is correct.

These are two issues which do not get covered in the book. You were not
missing anything, we just never coded for them. I believe there were
mentions somewhere in the chapters about this, but I don't have a copy in
front of me to verify where those might have been. I know the mentions were
small so they're easy to overlook! :)

Cheers,

Donn

On Wed, Dec 28, 2011 at 12:29 PM, Albertino <
reply@reply.github.com

**Comment by Albertino** [comment]
Hi Don,

First of all, thanks for your fast reply...appreciated! I just wanted to be
sure that I wasn't missing something :-)

I'm beginning with Android, so could you recommend me any good source to
help me with these two issues? I would like to sort them out as a
practice...

Best regards,
Albert
El 29/12/2011 0:40, "Donn Felker" <
reply@reply.github.com>
va escriure:
